project_id = "qhvxqmldpifwehnsrlyn"

[functions.qr-code-generator]
verify_jwt = true

[functions.event-check-in]
verify_jwt = true

[functions.event-messaging]
verify_jwt = true

[functions.webhook-handler]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.event-series-manager]
verify_jwt = true

[functions.bulk-event-operations]
verify_jwt = true

[functions.google-calendar-sync]
verify_jwt = true

[functions.meeting-integration]
verify_jwt = true

[functions.social-media-publisher]
verify_jwt = true

[functions.email-marketing-sync]
verify_jwt = true

[functions.omise-webhook]
verify_jwt = false

[functions.create-omise-charge]
verify_jwt = true

[functions.omise-refund]
verify_jwt = true

[functions.send-registration-email]
verify_jwt = true

[functions.auto-promote-waitlist]
verify_jwt = true

[functions.check-promotion-timeouts]
verify_jwt = false

[functions.scheduled-email-sender]
verify_jwt = false

[functions.event-reminder-scheduler]
verify_jwt = true

[functions.payment-reminder-handler]
verify_jwt = false

[functions.analytics-collector]
verify_jwt = true

[functions.metrics-aggregator]
verify_jwt = false

[functions.alert-processor]
verify_jwt = false

[functions.report-generator]
verify_jwt = true

[functions.ai-insights-generator]
verify_jwt = true

[functions.ai-chat-assistant]
verify_jwt = true

[functions.ai-event-recommendations]
verify_jwt = true

[functions.ai-event-creator]
verify_jwt = true

[functions.ai-smart-search]
verify_jwt = true
